version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # In development mode, mount volumes for hot reloading
      - .:/app:${FLASK_MOUNT:-ro}
      - ./templates:/app/templates:${FLASK_MOUNT:-ro}
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - PYTHONUNBUFFERED=1
    restart: ${RESTART_POLICY:-no}
    # Command is overridden by entrypoint.sh
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
