version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    # Use this command to enable hot-reloading during development
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload
