services:
  flask-app:
    build:
      context: .
      target: ${APP_ENV:-production}
    ports:
      - "5000:5000"
    volumes:
      # Single volume mount for the entire project
      - .:/app:ro
    environment:
      - FLASK_APP=app.py
      - APP_ENV=${APP_ENV:-production}
      - PYTHONUNBUFFERED=1
    restart: on-failure
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
